### ISSUE TITLE
Nvida Hardware support...

### ISSUE THREAD

**Issue by mrsieb** [FallingSnow/h265ize#100] opened 2017-06-07 20:16 UTC
Any change to take a benefit of this ?

http://www.phoronix.com/scan.php?page=news_item&px=FFmpeg-NVENC-H265-Encode

**Comment by FallingSnow** [comment] 2017-06-07 20:26
#75 addresses this. I did some testing with the latest generation cards, and while they are quick, they are very very limited in their options. You basically get a few presets and have to use that, hardware acceleration is mainly meant for streaming. Another thing is that they are not as efficient as software encoders, I haven't tested it in a while but I believe the difference is substantial.

The only real gain I see from using hw accel is decoding videos when necessary, and even then some of my tests showed similar cpu usage, along with the added gpu usage, as software decoding and slower than just using the cpu.

All in all this is something to look into but most likely will always be in the backlog till I find some real extra time and reason to do it.

Your not missing out on as much as you think.

**Comment by mrsieb** [comment] 2017-06-07 20:32
Well... many thx for that statement! Just looking forward to speed up to encode my let me say giant collection ;-) never mind will properly buy some bigger CPU :-D  and many thx for your job!! great tool!

**Comment by FallingSnow** [comment] 2017-06-08 01:44
Check out the new AMD and Intel CPU's that haven't come out yet. Encoders usually scale well and perform better the more cores you throw at them.

**Comment by charlas** [comment] 2017-07-06 20:46
Can agree there, work great on my Dual Xeon E5-2687W's :)

**Comment by FallingSnow** [comment] 2017-07-19 18:11
Duplicate of #75.

**Closed by FallingSnow** 2017-07-19 18:11 UTC
