### ISSUE TITLE
ffmpeg issue - Stream map matches no stream

### ISSUE THREAD

**Issue by azsde** [FallingSnow/h265ize#27] opened 2016-05-19 12:35 UTC
Hi,

I tried converting a bunch of movies, it works fine except for a few ones: after encoding with handbrake, ffmpeg causes an error:

> Stream map '0:3' matches no streams.
> To ignore this, add a trailing '?' to the map.
> [h265ize]: Ut oh. Ffmpeg exited with error code 1.
> [h265ize]: h265ize did not end cleanly. Deleting temp file and extra files.
> [h265ize]: [Debug] Temporary output at ./tempOutput/encoding-in-process-21637.mkv has not been deleted because you are in debug mode

Full debug log here:

[log.txt](https://github.com/FallingSnow/h265ize/files/272558/log.txt)

The temporary mkv file doesn't have any subtitles included in it.

How can I fix this ?

Regards,

Azsde.

**Comment by FallingSnow** [comment] 2016-05-23 00:27
Sorry @azsde, I meant to respond to your issue the first day you reported it but I forgot. I still have the message I wrote in the browser tab on my phone lol.

It seems handbrake isn't keeping your subtitles even though it is explicitly told to do so. Although these lines look a little suspect...

```
./h265ize: eval: ligne 641: erreur de syntaxe près du symbole inattendu « ( »
./h265ize: eval: ligne 641: `codec_name=dca codec_type=audio channels=6 avg_frame_rate=0/0 bits_per_raw_sample=24 TAG:title=Audio French (VFI=VFF) DTS 5.1 channels 24 bits @ 1509 Kbps cbr'
[h265ize]: [Debug] Stream Index: 1    Title: Audio French (VFI=VFF) DTS 5.1 channels 24 bits @ 1509 Kbps cbr    Language: fre    Codec: 
./h265ize: ligne 641: TAG:title=Audio : commande introuvable
```

I suggest you do one of two things. Upload a copy of the video you are trying to convert so I can debug it or look forward to [release 4.0](https://github.com/FallingSnow/h265ize/milestones/4.0), a lot of these random issues should be fixed with 4.0.

**Comment by azsde** [comment] 2016-05-23 15:34
I uploaded a copy on mega : https://mega.nz/#!JlpFyJ4Y!Lp-jikDPg5yBO3Idpd2Eq6izacmI1QIBGvf8RcSTfEs

The password is the name of your wonderful script :)

**Comment by FallingSnow** [comment] 2016-05-23 19:52
7.8 GB, holy cow! I'll get started on the download :P

**Closed** 2016-05-26 01:48 UTC
Labels: bug

**Comment by FallingSnow** [comment] 2016-05-26 01:50
Should be fixed now. Did a full encode of the video you provided just to be sure. Kind of funny, it was actually caused by the fact that one of the audio streams had a title with the word "channels" in it. This will no longer be a problem as of the latest version.

**Comment by azsde** [comment] 2016-05-26 08:49
Great I'm going ot test that !

You're the man ! ;-)

**Comment by FallingSnow** [comment] 2016-05-30 01:02
Hey Allan, I just saw your comments on my blog. Sorry my blog no long emails me when there is a new comment and idk how to fix it. Just wanted to say sorry I didn't see them earlier.
